# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.29)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS TKernel TKMath TKG2d TKG3d TKGeomBase TKBRep TKGeomAlgo TKTopAlgo TKPrim TKBO TKShHealing TKBool TKHLR TKFillet TKOffset TKFeat TKMesh TKXMesh TKCDF TKLCAF TKCAF TKBinL TKXmlL TKBin TKXml TKStdL TKStd TKTObj TKBinTObj TKXmlTObj TKVCAF TKService TKV3d TKXDE TKXSBase TKSTEPBase TKSTEPAttr TKSTEP209 TKSTEP TKIGES TKXCAF TKXDEIGES TKXDESTEP TKSTL TKVRML TKRWMesh TKXmlXCAF TKBinXCAF TKXDECascade TKExpress)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target TKernel
add_library(TKernel SHARED IMPORTED)

set_target_properties(TKernel PROPERTIES
  INTERFACE_LINK_LIBRARIES "advapi32.lib;gdi32.lib;user32.lib;wsock32.lib;psapi.lib"
)

# Create imported target TKMath
add_library(TKMath SHARED IMPORTED)

set_target_properties(TKMath PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel"
)

# Create imported target TKG2d
add_library(TKG2d SHARED IMPORTED)

set_target_properties(TKG2d PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKMath"
)

# Create imported target TKG3d
add_library(TKG3d SHARED IMPORTED)

set_target_properties(TKG3d PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKMath;TKernel;TKG2d"
)

# Create imported target TKGeomBase
add_library(TKGeomBase SHARED IMPORTED)

set_target_properties(TKGeomBase PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKMath;TKG2d;TKG3d"
)

# Create imported target TKBRep
add_library(TKBRep SHARED IMPORTED)

set_target_properties(TKBRep PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKMath;TKernel;TKG2d;TKG3d;TKGeomBase"
)

# Create imported target TKGeomAlgo
add_library(TKGeomAlgo SHARED IMPORTED)

set_target_properties(TKGeomAlgo PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKMath;TKG3d;TKG2d;TKGeomBase;TKBRep"
)

# Create imported target TKTopAlgo
add_library(TKTopAlgo SHARED IMPORTED)

set_target_properties(TKTopAlgo PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKMath;TKernel;TKG2d;TKG3d;TKGeomBase;TKBRep;TKGeomAlgo"
)

# Create imported target TKPrim
add_library(TKPrim SHARED IMPORTED)

set_target_properties(TKPrim PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKernel;TKMath;TKG2d;TKGeomBase;TKG3d;TKTopAlgo"
)

# Create imported target TKBO
add_library(TKBO SHARED IMPORTED)

set_target_properties(TKBO PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKTopAlgo;TKMath;TKernel;TKG2d;TKG3d;TKGeomAlgo;TKGeomBase;TKPrim;TKShHealing"
)

# Create imported target TKShHealing
add_library(TKShHealing SHARED IMPORTED)

set_target_properties(TKShHealing PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKernel;TKMath;TKG2d;TKTopAlgo;TKG3d;TKGeomBase;TKGeomAlgo;wsock32.lib"
)

# Create imported target TKBool
add_library(TKBool SHARED IMPORTED)

set_target_properties(TKBool PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKTopAlgo;TKMath;TKernel;TKPrim;TKG2d;TKG3d;TKShHealing;TKGeomBase;TKGeomAlgo;TKBO"
)

# Create imported target TKHLR
add_library(TKHLR SHARED IMPORTED)

set_target_properties(TKHLR PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKernel;TKMath;TKGeomBase;TKG2d;TKG3d;TKGeomAlgo;TKTopAlgo"
)

# Create imported target TKFillet
add_library(TKFillet SHARED IMPORTED)

set_target_properties(TKFillet PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKernel;TKMath;TKGeomBase;TKGeomAlgo;TKG2d;TKTopAlgo;TKG3d;TKBool;TKShHealing;TKBO"
)

# Create imported target TKOffset
add_library(TKOffset SHARED IMPORTED)

set_target_properties(TKOffset PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKFillet;TKBRep;TKTopAlgo;TKMath;TKernel;TKGeomBase;TKG2d;TKG3d;TKGeomAlgo;TKShHealing;TKBO;TKPrim;TKBool"
)

# Create imported target TKFeat
add_library(TKFeat SHARED IMPORTED)

set_target_properties(TKFeat PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKTopAlgo;TKGeomAlgo;TKMath;TKernel;TKGeomBase;TKPrim;TKG2d;TKBO;TKG3d;TKBool;TKShHealing"
)

# Create imported target TKMesh
add_library(TKMesh SHARED IMPORTED)

set_target_properties(TKMesh PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKMath;TKBRep;TKTopAlgo;TKShHealing;TKGeomBase;TKG3d;TKG2d"
)

# Create imported target TKXMesh
add_library(TKXMesh SHARED IMPORTED)

set_target_properties(TKXMesh PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKMath;TKernel;TKG2d;TKG3d;TKMesh"
)

# Create imported target TKCDF
add_library(TKCDF SHARED IMPORTED)

set_target_properties(TKCDF PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel"
)

# Create imported target TKLCAF
add_library(TKLCAF SHARED IMPORTED)

set_target_properties(TKLCAF PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKCDF;TKernel"
)

# Create imported target TKCAF
add_library(TKCAF SHARED IMPORTED)

set_target_properties(TKCAF PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKGeomBase;TKBRep;TKTopAlgo;TKMath;TKG2d;TKG3d;TKCDF;TKLCAF;TKBO"
)

# Create imported target TKBinL
add_library(TKBinL SHARED IMPORTED)

set_target_properties(TKBinL PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKCDF;TKernel;TKLCAF"
)

# Create imported target TKXmlL
add_library(TKXmlL SHARED IMPORTED)

set_target_properties(TKXmlL PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKCDF;TKernel;TKMath;TKLCAF"
)

# Create imported target TKBin
add_library(TKBin SHARED IMPORTED)

set_target_properties(TKBin PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKMath;TKernel;TKG2d;TKG3d;TKCAF;TKCDF;TKLCAF;TKBinL"
)

# Create imported target TKXml
add_library(TKXml SHARED IMPORTED)

set_target_properties(TKXml PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKCDF;TKernel;TKMath;TKBRep;TKG2d;TKGeomBase;TKG3d;TKLCAF;TKCAF;TKXmlL"
)

# Create imported target TKStdL
add_library(TKStdL SHARED IMPORTED)

set_target_properties(TKStdL PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKCDF;TKLCAF"
)

# Create imported target TKStd
add_library(TKStd SHARED IMPORTED)

set_target_properties(TKStd PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKCDF;TKCAF;TKLCAF;TKBRep;TKMath;TKG2d;TKG3d;TKStdL"
)

# Create imported target TKTObj
add_library(TKTObj SHARED IMPORTED)

set_target_properties(TKTObj PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKCDF;TKernel;TKMath;TKLCAF"
)

# Create imported target TKBinTObj
add_library(TKBinTObj SHARED IMPORTED)

set_target_properties(TKBinTObj PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKCDF;TKernel;TKTObj;TKMath;TKLCAF;TKBinL"
)

# Create imported target TKXmlTObj
add_library(TKXmlTObj SHARED IMPORTED)

set_target_properties(TKXmlTObj PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKCDF;TKernel;TKTObj;TKMath;TKLCAF;TKXmlL"
)

# Create imported target TKVCAF
add_library(TKVCAF SHARED IMPORTED)

set_target_properties(TKVCAF PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKGeomBase;TKBRep;TKTopAlgo;TKMath;TKService;TKG2d;TKG3d;TKCDF;TKLCAF;TKBO;TKCAF;TKV3d"
)

# Create imported target TKService
add_library(TKService SHARED IMPORTED)

set_target_properties(TKService PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKMath;user32.lib;advapi32.lib;advapi32.lib;user32.lib;windowscodecs;winmm.lib"
)

# Create imported target TKV3d
add_library(TKV3d SHARED IMPORTED)

set_target_properties(TKV3d PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKMath;TKernel;TKService;TKShHealing;TKTopAlgo;TKG2d;TKG3d;TKGeomBase;TKMesh;TKGeomAlgo;TKHLR;user32.lib;gdi32.lib;opengl32.lib"
)

# Create imported target TKXDE
add_library(TKXDE SHARED IMPORTED)

set_target_properties(TKXDE PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel"
)

# Create imported target TKXSBase
add_library(TKXSBase SHARED IMPORTED)

set_target_properties(TKXSBase PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKernel;TKMath;TKG2d;TKG3d;TKTopAlgo;TKGeomBase;TKShHealing"
)

# Create imported target TKSTEPBase
add_library(TKSTEPBase SHARED IMPORTED)

set_target_properties(TKSTEPBase PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKXSBase;TKMath"
)

# Create imported target TKSTEPAttr
add_library(TKSTEPAttr SHARED IMPORTED)

set_target_properties(TKSTEPAttr PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKXSBase;TKSTEPBase"
)

# Create imported target TKSTEP209
add_library(TKSTEP209 SHARED IMPORTED)

set_target_properties(TKSTEP209 PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKXSBase;TKSTEPBase"
)

# Create imported target TKSTEP
add_library(TKSTEP SHARED IMPORTED)

set_target_properties(TKSTEP PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKSTEPAttr;TKSTEP209;TKSTEPBase;TKBRep;TKMath;TKG2d;TKShHealing;TKTopAlgo;TKG3d;TKGeomBase;TKGeomAlgo;TKXSBase"
)

# Create imported target TKIGES
add_library(TKIGES SHARED IMPORTED)

set_target_properties(TKIGES PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKernel;TKMath;TKTopAlgo;TKShHealing;TKG2d;TKG3d;TKGeomBase;TKGeomAlgo;TKPrim;TKBool;TKXSBase"
)

# Create imported target TKXCAF
add_library(TKXCAF SHARED IMPORTED)

set_target_properties(TKXCAF PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKernel;TKMath;TKService;TKG2d;TKTopAlgo;TKV3d;TKCDF;TKLCAF;TKG3d;TKCAF;TKVCAF"
)

# Create imported target TKXDEIGES
add_library(TKXDEIGES SHARED IMPORTED)

set_target_properties(TKXDEIGES PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKXDE;TKernel;TKMath;TKXSBase;TKCDF;TKLCAF;TKG2d;TKG3d;TKXCAF;TKIGES"
)

# Create imported target TKXDESTEP
add_library(TKXDESTEP SHARED IMPORTED)

set_target_properties(TKXDESTEP PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKXDE;TKBRep;TKSTEPAttr;TKernel;TKMath;TKXSBase;TKTopAlgo;TKG2d;TKCAF;TKSTEPBase;TKCDF;TKLCAF;TKG3d;TKXCAF;TKSTEP;TKShHealing"
)

# Create imported target TKSTL
add_library(TKSTL SHARED IMPORTED)

set_target_properties(TKSTL PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKXDE;TKernel;TKMath;TKBRep;TKG2d;TKG3d;TKTopAlgo;TKLCAF;TKXCAF"
)

# Create imported target TKVRML
add_library(TKVRML SHARED IMPORTED)

set_target_properties(TKVRML PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKXDE;TKTopAlgo;TKMath;TKGeomBase;TKernel;TKPrim;TKG2d;TKG3d;TKMesh;TKHLR;TKRWMesh;TKService;TKGeomAlgo;TKV3d;TKLCAF;TKXCAF;TKXSBase"
)

# Create imported target TKRWMesh
add_library(TKRWMesh SHARED IMPORTED)

set_target_properties(TKRWMesh PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKMath;TKMesh;TKXCAF;TKLCAF;TKV3d;TKBRep;TKG3d;TKXDE;TKService"
)

# Create imported target TKXmlXCAF
add_library(TKXmlXCAF SHARED IMPORTED)

set_target_properties(TKXmlXCAF PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKXmlL;TKBRep;TKCDF;TKMath;TKernel;TKService;TKG2d;TKGeomBase;TKCAF;TKG3d;TKLCAF;TKXCAF;TKXml"
)

# Create imported target TKBinXCAF
add_library(TKBinXCAF SHARED IMPORTED)

set_target_properties(TKBinXCAF PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKXCAF;TKMath;TKService;TKernel;TKBinL;TKG2d;TKCAF;TKCDF;TKG3d;TKLCAF;TKBin"
)

# Create imported target TKXDECascade
add_library(TKXDECascade SHARED IMPORTED)

set_target_properties(TKXDECascade PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBin;TKBinL;TKBinTObj;TKBinXCAF;TKBRep;TKStd;TKXml;TKXmlL;TKXmlTObj;TKXmlXCAF;TKXDE;TKernel;TKMath;TKLCAF;TKXCAF;TKStdL;TKCDF"
)

# Create imported target TKExpress
add_library(TKExpress SHARED IMPORTED)

set_target_properties(TKExpress PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel"
)

# Import target "TKernel" for configuration "Release"
set_property(TARGET TKernel APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKernel PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKernel.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKernel.dll"
  )

# Import target "TKMath" for configuration "Release"
set_property(TARGET TKMath APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKMath PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKMath.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKMath.dll"
  )

# Import target "TKG2d" for configuration "Release"
set_property(TARGET TKG2d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKG2d PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKG2d.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKG2d.dll"
  )

# Import target "TKG3d" for configuration "Release"
set_property(TARGET TKG3d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKG3d PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKG3d.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKG3d.dll"
  )

# Import target "TKGeomBase" for configuration "Release"
set_property(TARGET TKGeomBase APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKGeomBase PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKGeomBase.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKGeomBase.dll"
  )

# Import target "TKBRep" for configuration "Release"
set_property(TARGET TKBRep APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKBRep PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKBRep.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKBRep.dll"
  )

# Import target "TKGeomAlgo" for configuration "Release"
set_property(TARGET TKGeomAlgo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKGeomAlgo PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKGeomAlgo.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKGeomAlgo.dll"
  )

# Import target "TKTopAlgo" for configuration "Release"
set_property(TARGET TKTopAlgo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKTopAlgo PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKTopAlgo.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKTopAlgo.dll"
  )

# Import target "TKPrim" for configuration "Release"
set_property(TARGET TKPrim APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKPrim PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKPrim.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKPrim.dll"
  )

# Import target "TKBO" for configuration "Release"
set_property(TARGET TKBO APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKBO PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKBO.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKBO.dll"
  )

# Import target "TKShHealing" for configuration "Release"
set_property(TARGET TKShHealing APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKShHealing PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKShHealing.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKShHealing.dll"
  )

# Import target "TKBool" for configuration "Release"
set_property(TARGET TKBool APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKBool PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKBool.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKBool.dll"
  )

# Import target "TKHLR" for configuration "Release"
set_property(TARGET TKHLR APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKHLR PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKHLR.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKHLR.dll"
  )

# Import target "TKFillet" for configuration "Release"
set_property(TARGET TKFillet APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKFillet PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKFillet.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKFillet.dll"
  )

# Import target "TKOffset" for configuration "Release"
set_property(TARGET TKOffset APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKOffset PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKOffset.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKOffset.dll"
  )

# Import target "TKFeat" for configuration "Release"
set_property(TARGET TKFeat APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKFeat PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKFeat.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKFeat.dll"
  )

# Import target "TKMesh" for configuration "Release"
set_property(TARGET TKMesh APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKMesh PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKMesh.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKMesh.dll"
  )

# Import target "TKXMesh" for configuration "Release"
set_property(TARGET TKXMesh APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXMesh PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKXMesh.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKXMesh.dll"
  )

# Import target "TKCDF" for configuration "Release"
set_property(TARGET TKCDF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKCDF PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKCDF.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKCDF.dll"
  )

# Import target "TKLCAF" for configuration "Release"
set_property(TARGET TKLCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKLCAF PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKLCAF.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKLCAF.dll"
  )

# Import target "TKCAF" for configuration "Release"
set_property(TARGET TKCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKCAF PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKCAF.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKCAF.dll"
  )

# Import target "TKBinL" for configuration "Release"
set_property(TARGET TKBinL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKBinL PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKBinL.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKBinL.dll"
  )

# Import target "TKXmlL" for configuration "Release"
set_property(TARGET TKXmlL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXmlL PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKXmlL.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKXmlL.dll"
  )

# Import target "TKBin" for configuration "Release"
set_property(TARGET TKBin APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKBin PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKBin.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKBin.dll"
  )

# Import target "TKXml" for configuration "Release"
set_property(TARGET TKXml APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXml PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKXml.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKXml.dll"
  )

# Import target "TKStdL" for configuration "Release"
set_property(TARGET TKStdL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKStdL PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKStdL.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKStdL.dll"
  )

# Import target "TKStd" for configuration "Release"
set_property(TARGET TKStd APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKStd PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKStd.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKStd.dll"
  )

# Import target "TKTObj" for configuration "Release"
set_property(TARGET TKTObj APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKTObj PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKTObj.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKTObj.dll"
  )

# Import target "TKBinTObj" for configuration "Release"
set_property(TARGET TKBinTObj APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKBinTObj PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKBinTObj.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKBinTObj.dll"
  )

# Import target "TKXmlTObj" for configuration "Release"
set_property(TARGET TKXmlTObj APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXmlTObj PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKXmlTObj.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKXmlTObj.dll"
  )

# Import target "TKVCAF" for configuration "Release"
set_property(TARGET TKVCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKVCAF PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKVCAF.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKVCAF.dll"
  )

# Import target "TKService" for configuration "Release"
set_property(TARGET TKService APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKService PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKService.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKService.dll"
  )

# Import target "TKV3d" for configuration "Release"
set_property(TARGET TKV3d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKV3d PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKV3d.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKV3d.dll"
  )

# Import target "TKXDE" for configuration "Release"
set_property(TARGET TKXDE APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXDE PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKXDE.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKXDE.dll"
  )

# Import target "TKXSBase" for configuration "Release"
set_property(TARGET TKXSBase APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXSBase PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKXSBase.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKXSBase.dll"
  )

# Import target "TKSTEPBase" for configuration "Release"
set_property(TARGET TKSTEPBase APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKSTEPBase PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKSTEPBase.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKSTEPBase.dll"
  )

# Import target "TKSTEPAttr" for configuration "Release"
set_property(TARGET TKSTEPAttr APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKSTEPAttr PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKSTEPAttr.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKSTEPAttr.dll"
  )

# Import target "TKSTEP209" for configuration "Release"
set_property(TARGET TKSTEP209 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKSTEP209 PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKSTEP209.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKSTEP209.dll"
  )

# Import target "TKSTEP" for configuration "Release"
set_property(TARGET TKSTEP APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKSTEP PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKSTEP.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKSTEP.dll"
  )

# Import target "TKIGES" for configuration "Release"
set_property(TARGET TKIGES APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKIGES PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKIGES.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKIGES.dll"
  )

# Import target "TKXCAF" for configuration "Release"
set_property(TARGET TKXCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXCAF PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKXCAF.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKXCAF.dll"
  )

# Import target "TKXDEIGES" for configuration "Release"
set_property(TARGET TKXDEIGES APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXDEIGES PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKXDEIGES.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKXDEIGES.dll"
  )

# Import target "TKXDESTEP" for configuration "Release"
set_property(TARGET TKXDESTEP APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXDESTEP PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKXDESTEP.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKXDESTEP.dll"
  )

# Import target "TKSTL" for configuration "Release"
set_property(TARGET TKSTL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKSTL PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKSTL.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKSTL.dll"
  )

# Import target "TKVRML" for configuration "Release"
set_property(TARGET TKVRML APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKVRML PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKVRML.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKVRML.dll"
  )

# Import target "TKRWMesh" for configuration "Release"
set_property(TARGET TKRWMesh APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKRWMesh PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKRWMesh.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKRWMesh.dll"
  )

# Import target "TKXmlXCAF" for configuration "Release"
set_property(TARGET TKXmlXCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXmlXCAF PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKXmlXCAF.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKXmlXCAF.dll"
  )

# Import target "TKBinXCAF" for configuration "Release"
set_property(TARGET TKBinXCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKBinXCAF PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKBinXCAF.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKBinXCAF.dll"
  )

# Import target "TKXDECascade" for configuration "Release"
set_property(TARGET TKXDECascade APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXDECascade PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKXDECascade.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKXDECascade.dll"
  )

# Import target "TKExpress" for configuration "Release"
set_property(TARGET TKExpress APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKExpress PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/OCCT-Build/Builds/win64/vc14/lib/TKExpress.lib"
  IMPORTED_LOCATION_RELEASE "C:/OCCT-Build/Builds/win64/vc14/bin/TKExpress.dll"
  )

# Import target "TKernel" for configuration "Debug"
set_property(TARGET TKernel APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKernel PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKernel.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKernel.dll"
  )

# Import target "TKMath" for configuration "Debug"
set_property(TARGET TKMath APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKMath PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKMath.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKMath.dll"
  )

# Import target "TKG2d" for configuration "Debug"
set_property(TARGET TKG2d APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKG2d PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKG2d.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKG2d.dll"
  )

# Import target "TKG3d" for configuration "Debug"
set_property(TARGET TKG3d APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKG3d PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKG3d.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKG3d.dll"
  )

# Import target "TKGeomBase" for configuration "Debug"
set_property(TARGET TKGeomBase APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKGeomBase PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKGeomBase.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKGeomBase.dll"
  )

# Import target "TKBRep" for configuration "Debug"
set_property(TARGET TKBRep APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKBRep PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKBRep.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKBRep.dll"
  )

# Import target "TKGeomAlgo" for configuration "Debug"
set_property(TARGET TKGeomAlgo APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKGeomAlgo PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKGeomAlgo.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKGeomAlgo.dll"
  )

# Import target "TKTopAlgo" for configuration "Debug"
set_property(TARGET TKTopAlgo APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKTopAlgo PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKTopAlgo.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKTopAlgo.dll"
  )

# Import target "TKPrim" for configuration "Debug"
set_property(TARGET TKPrim APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKPrim PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKPrim.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKPrim.dll"
  )

# Import target "TKBO" for configuration "Debug"
set_property(TARGET TKBO APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKBO PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKBO.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKBO.dll"
  )

# Import target "TKShHealing" for configuration "Debug"
set_property(TARGET TKShHealing APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKShHealing PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKShHealing.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKShHealing.dll"
  )

# Import target "TKBool" for configuration "Debug"
set_property(TARGET TKBool APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKBool PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKBool.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKBool.dll"
  )

# Import target "TKHLR" for configuration "Debug"
set_property(TARGET TKHLR APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKHLR PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKHLR.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKHLR.dll"
  )

# Import target "TKFillet" for configuration "Debug"
set_property(TARGET TKFillet APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKFillet PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKFillet.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKFillet.dll"
  )

# Import target "TKOffset" for configuration "Debug"
set_property(TARGET TKOffset APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKOffset PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKOffset.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKOffset.dll"
  )

# Import target "TKFeat" for configuration "Debug"
set_property(TARGET TKFeat APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKFeat PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKFeat.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKFeat.dll"
  )

# Import target "TKMesh" for configuration "Debug"
set_property(TARGET TKMesh APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKMesh PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKMesh.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKMesh.dll"
  )

# Import target "TKXMesh" for configuration "Debug"
set_property(TARGET TKXMesh APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKXMesh PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKXMesh.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKXMesh.dll"
  )

# Import target "TKCDF" for configuration "Debug"
set_property(TARGET TKCDF APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKCDF PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKCDF.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKCDF.dll"
  )

# Import target "TKLCAF" for configuration "Debug"
set_property(TARGET TKLCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKLCAF PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKLCAF.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKLCAF.dll"
  )

# Import target "TKCAF" for configuration "Debug"
set_property(TARGET TKCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKCAF PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKCAF.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKCAF.dll"
  )

# Import target "TKBinL" for configuration "Debug"
set_property(TARGET TKBinL APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKBinL PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKBinL.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKBinL.dll"
  )

# Import target "TKXmlL" for configuration "Debug"
set_property(TARGET TKXmlL APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKXmlL PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKXmlL.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKXmlL.dll"
  )

# Import target "TKBin" for configuration "Debug"
set_property(TARGET TKBin APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKBin PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKBin.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKBin.dll"
  )

# Import target "TKXml" for configuration "Debug"
set_property(TARGET TKXml APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKXml PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKXml.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKXml.dll"
  )

# Import target "TKStdL" for configuration "Debug"
set_property(TARGET TKStdL APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKStdL PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKStdL.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKStdL.dll"
  )

# Import target "TKStd" for configuration "Debug"
set_property(TARGET TKStd APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKStd PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKStd.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKStd.dll"
  )

# Import target "TKTObj" for configuration "Debug"
set_property(TARGET TKTObj APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKTObj PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKTObj.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKTObj.dll"
  )

# Import target "TKBinTObj" for configuration "Debug"
set_property(TARGET TKBinTObj APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKBinTObj PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKBinTObj.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKBinTObj.dll"
  )

# Import target "TKXmlTObj" for configuration "Debug"
set_property(TARGET TKXmlTObj APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKXmlTObj PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKXmlTObj.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKXmlTObj.dll"
  )

# Import target "TKVCAF" for configuration "Debug"
set_property(TARGET TKVCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKVCAF PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKVCAF.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKVCAF.dll"
  )

# Import target "TKService" for configuration "Debug"
set_property(TARGET TKService APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKService PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKService.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKService.dll"
  )

# Import target "TKV3d" for configuration "Debug"
set_property(TARGET TKV3d APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKV3d PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKV3d.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKV3d.dll"
  )

# Import target "TKXDE" for configuration "Debug"
set_property(TARGET TKXDE APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKXDE PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKXDE.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKXDE.dll"
  )

# Import target "TKXSBase" for configuration "Debug"
set_property(TARGET TKXSBase APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKXSBase PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKXSBase.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKXSBase.dll"
  )

# Import target "TKSTEPBase" for configuration "Debug"
set_property(TARGET TKSTEPBase APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKSTEPBase PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKSTEPBase.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKSTEPBase.dll"
  )

# Import target "TKSTEPAttr" for configuration "Debug"
set_property(TARGET TKSTEPAttr APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKSTEPAttr PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKSTEPAttr.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKSTEPAttr.dll"
  )

# Import target "TKSTEP209" for configuration "Debug"
set_property(TARGET TKSTEP209 APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKSTEP209 PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKSTEP209.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKSTEP209.dll"
  )

# Import target "TKSTEP" for configuration "Debug"
set_property(TARGET TKSTEP APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKSTEP PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKSTEP.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKSTEP.dll"
  )

# Import target "TKIGES" for configuration "Debug"
set_property(TARGET TKIGES APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKIGES PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKIGES.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKIGES.dll"
  )

# Import target "TKXCAF" for configuration "Debug"
set_property(TARGET TKXCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKXCAF PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKXCAF.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKXCAF.dll"
  )

# Import target "TKXDEIGES" for configuration "Debug"
set_property(TARGET TKXDEIGES APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKXDEIGES PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKXDEIGES.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKXDEIGES.dll"
  )

# Import target "TKXDESTEP" for configuration "Debug"
set_property(TARGET TKXDESTEP APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKXDESTEP PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKXDESTEP.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKXDESTEP.dll"
  )

# Import target "TKSTL" for configuration "Debug"
set_property(TARGET TKSTL APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKSTL PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKSTL.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKSTL.dll"
  )

# Import target "TKVRML" for configuration "Debug"
set_property(TARGET TKVRML APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKVRML PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKVRML.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKVRML.dll"
  )

# Import target "TKRWMesh" for configuration "Debug"
set_property(TARGET TKRWMesh APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKRWMesh PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKRWMesh.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKRWMesh.dll"
  )

# Import target "TKXmlXCAF" for configuration "Debug"
set_property(TARGET TKXmlXCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKXmlXCAF PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKXmlXCAF.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKXmlXCAF.dll"
  )

# Import target "TKBinXCAF" for configuration "Debug"
set_property(TARGET TKBinXCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKBinXCAF PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKBinXCAF.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKBinXCAF.dll"
  )

# Import target "TKXDECascade" for configuration "Debug"
set_property(TARGET TKXDECascade APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKXDECascade PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKXDECascade.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKXDECascade.dll"
  )

# Import target "TKExpress" for configuration "Debug"
set_property(TARGET TKExpress APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKExpress PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/OCCT-Build/Builds/win64/vc14/libd/TKExpress.lib"
  IMPORTED_LOCATION_DEBUG "C:/OCCT-Build/Builds/win64/vc14/bind/TKExpress.dll"
  )

# Import target "TKernel" for configuration "RelWithDebInfo"
set_property(TARGET TKernel APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKernel PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKernel.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKernel.dll"
  )

# Import target "TKMath" for configuration "RelWithDebInfo"
set_property(TARGET TKMath APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKMath PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKMath.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKMath.dll"
  )

# Import target "TKG2d" for configuration "RelWithDebInfo"
set_property(TARGET TKG2d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKG2d PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKG2d.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKG2d.dll"
  )

# Import target "TKG3d" for configuration "RelWithDebInfo"
set_property(TARGET TKG3d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKG3d PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKG3d.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKG3d.dll"
  )

# Import target "TKGeomBase" for configuration "RelWithDebInfo"
set_property(TARGET TKGeomBase APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKGeomBase PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKGeomBase.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKGeomBase.dll"
  )

# Import target "TKBRep" for configuration "RelWithDebInfo"
set_property(TARGET TKBRep APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKBRep PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKBRep.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKBRep.dll"
  )

# Import target "TKGeomAlgo" for configuration "RelWithDebInfo"
set_property(TARGET TKGeomAlgo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKGeomAlgo PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKGeomAlgo.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKGeomAlgo.dll"
  )

# Import target "TKTopAlgo" for configuration "RelWithDebInfo"
set_property(TARGET TKTopAlgo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKTopAlgo PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKTopAlgo.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKTopAlgo.dll"
  )

# Import target "TKPrim" for configuration "RelWithDebInfo"
set_property(TARGET TKPrim APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKPrim PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKPrim.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKPrim.dll"
  )

# Import target "TKBO" for configuration "RelWithDebInfo"
set_property(TARGET TKBO APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKBO PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKBO.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKBO.dll"
  )

# Import target "TKShHealing" for configuration "RelWithDebInfo"
set_property(TARGET TKShHealing APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKShHealing PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKShHealing.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKShHealing.dll"
  )

# Import target "TKBool" for configuration "RelWithDebInfo"
set_property(TARGET TKBool APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKBool PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKBool.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKBool.dll"
  )

# Import target "TKHLR" for configuration "RelWithDebInfo"
set_property(TARGET TKHLR APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKHLR PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKHLR.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKHLR.dll"
  )

# Import target "TKFillet" for configuration "RelWithDebInfo"
set_property(TARGET TKFillet APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKFillet PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKFillet.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKFillet.dll"
  )

# Import target "TKOffset" for configuration "RelWithDebInfo"
set_property(TARGET TKOffset APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKOffset PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKOffset.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKOffset.dll"
  )

# Import target "TKFeat" for configuration "RelWithDebInfo"
set_property(TARGET TKFeat APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKFeat PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKFeat.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKFeat.dll"
  )

# Import target "TKMesh" for configuration "RelWithDebInfo"
set_property(TARGET TKMesh APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKMesh PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKMesh.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKMesh.dll"
  )

# Import target "TKXMesh" for configuration "RelWithDebInfo"
set_property(TARGET TKXMesh APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKXMesh PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKXMesh.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKXMesh.dll"
  )

# Import target "TKCDF" for configuration "RelWithDebInfo"
set_property(TARGET TKCDF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKCDF PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKCDF.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKCDF.dll"
  )

# Import target "TKLCAF" for configuration "RelWithDebInfo"
set_property(TARGET TKLCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKLCAF PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKLCAF.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKLCAF.dll"
  )

# Import target "TKCAF" for configuration "RelWithDebInfo"
set_property(TARGET TKCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKCAF PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKCAF.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKCAF.dll"
  )

# Import target "TKBinL" for configuration "RelWithDebInfo"
set_property(TARGET TKBinL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKBinL PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKBinL.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKBinL.dll"
  )

# Import target "TKXmlL" for configuration "RelWithDebInfo"
set_property(TARGET TKXmlL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKXmlL PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKXmlL.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKXmlL.dll"
  )

# Import target "TKBin" for configuration "RelWithDebInfo"
set_property(TARGET TKBin APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKBin PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKBin.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKBin.dll"
  )

# Import target "TKXml" for configuration "RelWithDebInfo"
set_property(TARGET TKXml APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKXml PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKXml.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKXml.dll"
  )

# Import target "TKStdL" for configuration "RelWithDebInfo"
set_property(TARGET TKStdL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKStdL PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKStdL.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKStdL.dll"
  )

# Import target "TKStd" for configuration "RelWithDebInfo"
set_property(TARGET TKStd APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKStd PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKStd.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKStd.dll"
  )

# Import target "TKTObj" for configuration "RelWithDebInfo"
set_property(TARGET TKTObj APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKTObj PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKTObj.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKTObj.dll"
  )

# Import target "TKBinTObj" for configuration "RelWithDebInfo"
set_property(TARGET TKBinTObj APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKBinTObj PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKBinTObj.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKBinTObj.dll"
  )

# Import target "TKXmlTObj" for configuration "RelWithDebInfo"
set_property(TARGET TKXmlTObj APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKXmlTObj PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKXmlTObj.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKXmlTObj.dll"
  )

# Import target "TKVCAF" for configuration "RelWithDebInfo"
set_property(TARGET TKVCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKVCAF PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKVCAF.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKVCAF.dll"
  )

# Import target "TKService" for configuration "RelWithDebInfo"
set_property(TARGET TKService APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKService PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKService.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKService.dll"
  )

# Import target "TKV3d" for configuration "RelWithDebInfo"
set_property(TARGET TKV3d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKV3d PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKV3d.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKV3d.dll"
  )

# Import target "TKXDE" for configuration "RelWithDebInfo"
set_property(TARGET TKXDE APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKXDE PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKXDE.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKXDE.dll"
  )

# Import target "TKXSBase" for configuration "RelWithDebInfo"
set_property(TARGET TKXSBase APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKXSBase PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKXSBase.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKXSBase.dll"
  )

# Import target "TKSTEPBase" for configuration "RelWithDebInfo"
set_property(TARGET TKSTEPBase APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKSTEPBase PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKSTEPBase.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKSTEPBase.dll"
  )

# Import target "TKSTEPAttr" for configuration "RelWithDebInfo"
set_property(TARGET TKSTEPAttr APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKSTEPAttr PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKSTEPAttr.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKSTEPAttr.dll"
  )

# Import target "TKSTEP209" for configuration "RelWithDebInfo"
set_property(TARGET TKSTEP209 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKSTEP209 PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKSTEP209.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKSTEP209.dll"
  )

# Import target "TKSTEP" for configuration "RelWithDebInfo"
set_property(TARGET TKSTEP APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKSTEP PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKSTEP.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKSTEP.dll"
  )

# Import target "TKIGES" for configuration "RelWithDebInfo"
set_property(TARGET TKIGES APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKIGES PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKIGES.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKIGES.dll"
  )

# Import target "TKXCAF" for configuration "RelWithDebInfo"
set_property(TARGET TKXCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKXCAF PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKXCAF.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKXCAF.dll"
  )

# Import target "TKXDEIGES" for configuration "RelWithDebInfo"
set_property(TARGET TKXDEIGES APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKXDEIGES PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKXDEIGES.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKXDEIGES.dll"
  )

# Import target "TKXDESTEP" for configuration "RelWithDebInfo"
set_property(TARGET TKXDESTEP APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKXDESTEP PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKXDESTEP.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKXDESTEP.dll"
  )

# Import target "TKSTL" for configuration "RelWithDebInfo"
set_property(TARGET TKSTL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKSTL PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKSTL.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKSTL.dll"
  )

# Import target "TKVRML" for configuration "RelWithDebInfo"
set_property(TARGET TKVRML APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKVRML PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKVRML.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKVRML.dll"
  )

# Import target "TKRWMesh" for configuration "RelWithDebInfo"
set_property(TARGET TKRWMesh APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKRWMesh PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKRWMesh.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKRWMesh.dll"
  )

# Import target "TKXmlXCAF" for configuration "RelWithDebInfo"
set_property(TARGET TKXmlXCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKXmlXCAF PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKXmlXCAF.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKXmlXCAF.dll"
  )

# Import target "TKBinXCAF" for configuration "RelWithDebInfo"
set_property(TARGET TKBinXCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKBinXCAF PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKBinXCAF.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKBinXCAF.dll"
  )

# Import target "TKXDECascade" for configuration "RelWithDebInfo"
set_property(TARGET TKXDECascade APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKXDECascade PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKXDECascade.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKXDECascade.dll"
  )

# Import target "TKExpress" for configuration "RelWithDebInfo"
set_property(TARGET TKExpress APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TKExpress PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/libi/TKExpress.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/OCCT-Build/Builds/win64/vc14/bini/TKExpress.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
